### ISSUE TITLE
Add Henderson filters to the package

### ISSUE THREAD

**Issue by vly** [viraltux/Forecast.jl#14]
Would like to add functionality for Henderson filters for smoothing deseasonalised timeseries data.

_Reference:_
[ABS - Time Series Analysis: The Process of Seasonal Adjustment](https://www.abs.gov.au/websitedbs/d3310114.nsf/4a256353001af3ed4b2562bb00121564/5fc845406def2c3dca256ce100188f8e!OpenDocument)

**Comment by viraltux** [comment]
Awesome! Bring it on!

**Comment by viraltux** [comment]
.

**Comment by viraltux** [comment]
Hi @vly , I was doing some refactoring and I checked the github place you used to port the hma code to Julia to make sure it has MIT license and we can use it. However there seems to be no repo sharing anything related to hma there. Is this the correct address (https://github.com/bpalmer4) ?

**Comment by vly** [comment]
hey @viraltux , ah, I think it was [here](https://github.com/bpalmer4/Covid-19/blob/master/bin/Henderson.py).

**Comment by viraltux** [comment]
Oh! great ,thanks @vly for the link, I updated the license accordingly.
